Repository gfx-rs/wgpu, pull requests merged in 2023-12, with the labels that each got.

#4818 Fix `BufferMapRange` not being Send/Sync (on native)
  CHANGELOG.md
  wgpu/src/backend/web.rs
  wgpu/src/context.rs
Labels: area: api

#4863 [naga wgsl-out] Include the `i` suffix on `i32` literals.
  CHANGELOG.md
  naga/src/back/wgsl/writer.rs
  naga/tests/out/wgsl/900-implicit-conversions.frag.wgsl
  naga/tests/out/wgsl/931-constant-emitting.frag.wgsl
  naga/tests/out/wgsl/932-for-loop-if.frag.wgsl
  naga/tests/out/wgsl/abstract-types-const.wgsl
  naga/tests/out/wgsl/abstract-types-var.wgsl
  naga/tests/out/wgsl/access.wgsl
  naga/tests/out/wgsl/atomicOps.wgsl
  naga/tests/out/wgsl/bevy-pbr.frag.wgsl
  naga/tests/out/wgsl/binding-arrays.dynamic.wgsl
  naga/tests/out/wgsl/binding-arrays.static.wgsl
  naga/tests/out/wgsl/binding-arrays.wgsl
  naga/tests/out/wgsl/bitcast.wgsl
  naga/tests/out/wgsl/bits.wgsl
  naga/tests/out/wgsl/bits_glsl.frag.wgsl
  naga/tests/out/wgsl/boids.wgsl
  naga/tests/out/wgsl/buffer.frag.wgsl
  naga/tests/out/wgsl/const-exprs.wgsl
  naga/tests/out/wgsl/constant-array-size.frag.wgsl
  naga/tests/out/wgsl/constructors.wgsl
  naga/tests/out/wgsl/control-flow.wgsl
  naga/tests/out/wgsl/declarations.frag.wgsl
  naga/tests/out/wgsl/double-math-functions.frag.wgsl
  naga/tests/out/wgsl/empty-global-name.wgsl
  naga/tests/out/wgsl/expressions.frag.wgsl
  naga/tests/out/wgsl/fragment-output.wgsl
  naga/tests/out/wgsl/functions.wgsl
  naga/tests/out/wgsl/globals.wgsl
  naga/tests/out/wgsl/image.wgsl
  naga/tests/out/wgsl/lexical-scopes.wgsl
  naga/tests/out/wgsl/local-var-init-in-loop.comp.wgsl
  naga/tests/out/wgsl/math-functions.frag.wgsl
  naga/tests/out/wgsl/math-functions.wgsl
  naga/tests/out/wgsl/module-scope.wgsl
  naga/tests/out/wgsl/operators.wgsl
  naga/tests/out/wgsl/pointers.wgsl
  naga/tests/out/wgsl/prepostfix.frag.wgsl
  naga/tests/out/wgsl/samplers.frag.wgsl
  naga/tests/out/wgsl/skybox.wgsl
  naga/tests/out/wgsl/workgroup-uniform-load.wgsl
Labels: area: naga back-end, naga, lang: WGSL

#4886 Document wgpu & wgpu-core features
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  wgpu-core/Cargo.toml
  wgpu-core/src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/lib.rs
Labels: area: documentation

#4924 Inline `document-features` usage, remove dep.
  Cargo.lock
  Cargo.toml
  wgpu-core/Cargo.toml
  wgpu-core/src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/lib.rs
Labels: type: bug, area: infrastructure, area: documentation, kind: refactor
