Repository gfx-rs/wgpu, pull requests merged in 2023-09, with the labels that each got.

#4106 Fix D3D12 Surface Leak
  wgpu-core/src/device/global.rs
  wgpu-core/src/device/mod.rs
  wgpu-core/src/present.rs
  wgpu-hal/src/dx12/device.rs
  wgpu-hal/src/dx12/mod.rs
  wgpu-hal/src/lib.rs
  wgpu-hal/src/vulkan/device.rs
  wgpu-hal/src/vulkan/instance.rs
Labels: needs back-porting

#4145 Add details to `RequestDeviceError`.
  CHANGELOG.md
  tests/src/lib.rs
  tests/tests/device.rs
  wgpu/src/backend/direct.rs
  wgpu/src/backend/web.rs
  wgpu/src/lib.rs
Labels: PR: waiting for review

#4008 Metal encoder & pass timestamp support
  .deny.toml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  examples/timestamp-queries/src/main.rs
  wgpu-hal/src/metal/adapter.rs
  wgpu-hal/src/metal/command.rs
  wgpu-hal/src/metal/mod.rs
  wgpu-types/src/lib.rs
Labels: PR: waiting for author

#4147 Make `StoreOp` an enum instead of a bool
  CHANGELOG.md
  examples/boids/src/main.rs
  examples/bunnymark/src/main.rs
  examples/capture/src/main.rs
  examples/conservative-raster/src/main.rs
  examples/cube/src/main.rs
  examples/hello-triangle/src/main.rs
  examples/hello-windows/src/main.rs
  examples/mipmap/src/main.rs
  examples/msaa-line/src/main.rs
  examples/shadow/src/main.rs
  examples/skybox/src/main.rs
  examples/stencil-triangles/src/main.rs
  examples/texture-arrays/src/main.rs
  examples/timestamp-queries/src/main.rs
  examples/water/src/main.rs
  tests/tests/occlusion_query/mod.rs
  tests/tests/regression/issue_3457.rs
  tests/tests/scissor_tests/mod.rs
  tests/tests/shader_primitive_index/mod.rs
  tests/tests/zero_init_texture_after_discard.rs
  wgpu/src/backend/direct.rs
  wgpu/src/backend/web.rs
  wgpu/src/lib.rs
Labels: PR: waiting for review

#4022 Support dual source blending
  CHANGELOG.md
  wgpu-core/src/device/resource.rs
  wgpu-core/src/pipeline.rs
  wgpu-core/src/validation.rs
  wgpu-hal/src/dx12/adapter.rs
  wgpu-hal/src/dx12/conv.rs
  wgpu-hal/src/gles/adapter.rs
  wgpu-hal/src/gles/conv.rs
  wgpu-hal/src/metal/adapter.rs
  wgpu-hal/src/metal/conv.rs
  wgpu-hal/src/vulkan/adapter.rs
  wgpu-hal/src/vulkan/conv.rs
  wgpu-types/src/lib.rs
  wgpu/src/backend/web.rs
Labels: PR: waiting for author

#4116 wgpu-core: Only produce StageError::InputNotConsumed on DX11/DX12
  CHANGELOG.md
  deno_webgpu/lib.rs
  wgpu-core/src/device/resource.rs
  wgpu-core/src/validation.rs
  wgpu-hal/src/gles/adapter.rs
  wgpu-hal/src/metal/adapter.rs
  wgpu-hal/src/vulkan/adapter.rs
  wgpu-types/src/lib.rs
Labels: PR: waiting for author
