Repository gfx-rs/wgpu, pull requests merged in 2024-01, with the labels that each got.

#4899 Expose maximum_frame_latency
  CHANGELOG.md
  examples/src/framework.rs
  examples/src/hello_triangle/mod.rs
  examples/src/hello_windows/mod.rs
  examples/src/uniform_values/mod.rs
  wgpu-core/src/device/global.rs
  wgpu-core/src/present.rs
  wgpu-hal/examples/halmark/main.rs
  wgpu-hal/examples/ray-traced-triangle/main.rs
  wgpu-hal/src/dx12/adapter.rs
  wgpu-hal/src/dx12/mod.rs
  wgpu-hal/src/gles/adapter.rs
  wgpu-hal/src/lib.rs
  wgpu-hal/src/metal/adapter.rs
  wgpu-hal/src/metal/surface.rs
  wgpu-hal/src/vulkan/adapter.rs
  wgpu-hal/src/vulkan/device.rs
  wgpu-types/src/lib.rs
  wgpu/src/lib.rs
Labels: area: api

#5104 Error on missing web_sys_unstable_apis
  .cargo/config.toml
  .github/workflows/ci.yml
  wgpu/src/backend/mod.rs
  wgpu/src/lib.rs
Labels: PR: needs back-porting

#5093 Document Wayland specifics related to SurfaceTexture::present
  CHANGELOG.md
  wgpu/src/lib.rs
Labels: PR: needs back-porting

#4967 vulkan: Replace fence with semaphore when acquiring surfaces
  wgpu-core/src/device/queue.rs
  wgpu-hal/examples/halmark/main.rs
  wgpu-hal/examples/raw-gles.rs
  wgpu-hal/examples/ray-traced-triangle/main.rs
  wgpu-hal/src/dx12/mod.rs
  wgpu-hal/src/empty.rs
  wgpu-hal/src/gles/queue.rs
  wgpu-hal/src/lib.rs
  wgpu-hal/src/metal/mod.rs
  wgpu-hal/src/vulkan/device.rs
  wgpu-hal/src/vulkan/instance.rs
  wgpu-hal/src/vulkan/mod.rs
Labels: PR: needs back-porting

#5103 fix(const_eval): use component count, not arg. count, for component-wise iter.
  naga/src/proc/constant_evaluator.rs
Labels: type: bug, area: correctness, area: naga processing

#5166 Fix panic when creating a surface while no backend is available
  CHANGELOG.md
  wgpu-core/src/instance.rs
  wgpu/src/lib.rs
Labels: type: bug

#5167 Allow wgpu::Instance to report which backends were enabled
  CHANGELOG.md
  wgpu/Cargo.toml
  wgpu/src/lib.rs
Labels: type: enhancement
