Repository gfx-rs/wgpu, pull requests merged in 2024-04, with the labels that each got.

#5475 fix: unlock guard for `release_gpu_resources` call in `Device::maintain`
  tests/tests/device.rs
  wgpu-core/src/device/global.rs
  wgpu-core/src/device/queue.rs
  wgpu-core/src/device/resource.rs
Labels: type: bug, area: correctness

#5495 [naga] Permit override expressions as `LocalVariable` initializers.
  naga/src/back/pipeline_constants.rs
  naga/src/front/wgsl/lower/mod.rs
  naga/src/lib.rs
  naga/src/valid/function.rs
  naga/tests/out/analysis/overrides.info.ron
  naga/tests/out/glsl/overrides.main.Compute.glsl
  naga/tests/out/hlsl/overrides.hlsl
  naga/tests/out/ir/overrides.compact.ron
  naga/tests/out/ir/overrides.ron
  naga/tests/out/msl/overrides.msl
  naga/tests/out/spv/overrides.main.spvasm
Labels: naga, area: naga front-end, lang: WGSL

#5513 [core] Use `expect` instead of "if let else panic".
  wgpu-core/src/command/mod.rs
  wgpu-core/src/device/queue.rs
  wgpu-core/src/global.rs
  wgpu-core/src/instance.rs
Labels: kind: refactor

#5511 water test: Expect additional error from GPU validation.
  examples/src/water/mod.rs
Labels: area: validation, api: vulkan, area: tests

#5524 [hal] Update crate documentation and wgpu-hal/README.md.
  wgpu-hal/README.md
  wgpu-hal/src/lib.rs
Labels: area: documentation

#5455 BACKPORT to 0.19: fix: don't depend on BG{,L} layout entry order in HAL #5421
  CHANGELOG.md
  Cargo.lock
  tests/tests/device.rs
  wgpu-hal/src/dx12/device.rs
  wgpu-hal/src/gles/device.rs
  wgpu-hal/src/metal/device.rs
Labels: type: bug, PR: needs back-porting, area: correctness, api: dx12, api: metal, api: gles

#5561 [core] Document deferred retention strategy for `ActiveSubmission`.
  wgpu-core/src/device/life.rs
Labels: area: documentation

#5562 [core] Make `cargo doc --document-private-items` work again.
  .github/workflows/ci.yml
  wgpu-core/src/command/allocator.rs
  wgpu-core/src/command/bundle.rs
  wgpu-core/src/command/mod.rs
  wgpu-core/src/device/bgl.rs
  wgpu-core/src/device/life.rs
  wgpu-core/src/device/queue.rs
  wgpu-core/src/identity.rs
  wgpu-core/src/pool.rs
  wgpu-core/src/registry.rs
  wgpu-core/src/track/mod.rs
Labels: area: documentation

#5539 [core] Enforce a deadlock-free locking order for Mutexes.
  wgpu-core/src/command/allocator.rs
  wgpu-core/src/command/mod.rs
  wgpu-core/src/device/life.rs
  wgpu-core/src/device/queue.rs
  wgpu-core/src/device/resource.rs
  wgpu-core/src/identity.rs
  wgpu-core/src/instance.rs
  wgpu-core/src/lib.rs
  wgpu-core/src/lock/mod.rs
  wgpu-core/src/lock/rank.rs
  wgpu-core/src/lock/ranked.rs
  wgpu-core/src/lock/vanilla.rs
  wgpu-core/src/pool.rs
  wgpu-core/src/present.rs
  wgpu-core/src/resource.rs
  wgpu-core/src/track/buffer.rs
  wgpu-core/src/track/mod.rs
  wgpu-core/src/track/stateless.rs
  wgpu-core/src/track/texture.rs
Labels: area: correctness

#5617 [hal] Fix `cargo doc --document-private-items`. Check in CI.
  .github/workflows/ci.yml
  CHANGELOG.md
  wgpu-hal/src/dx12/conv.rs
  wgpu-hal/src/dx12/mod.rs
  wgpu-hal/src/metal/mod.rs
  wgpu-hal/src/vulkan/adapter.rs
Labels: area: documentation

#5612 refactor(naga): remove extraneous leading path qualifiers
  naga/src/proc/constant_evaluator.rs
  naga/src/proc/index.rs
  naga/src/span.rs
  naga/src/valid/analyzer.rs
  naga/src/valid/expression.rs
Labels: naga, kind: refactor

#5640 Cast ptr to Device not Surface
  wgpu-core/src/device/any_device.rs
Labels: PR: needs back-porting
