Repository gfx-rs/wgpu, pull requests merged in 2024-08, with the labels that each got.

#6121 refactor(web): satisfy `unused_qualifications`
  wgpu-hal/src/gles/web.rs
Labels: kind: refactor

#6136 Make `wgpu_test::valid` print errors it detects.
  tests/src/lib.rs
Labels: area: infrastructure

#6146 Reduce size of parse error
  naga/src/front/wgsl/error.rs
  naga/src/front/wgsl/lower/construction.rs
  naga/src/front/wgsl/lower/conversion.rs
  naga/src/front/wgsl/lower/mod.rs
Labels: area: performance, naga, area: naga front-end, lang: WGSL
