Repository gfx-rs/wgpu, pull requests merged in 2024-02, with the labels that each got.

#5176 Ord for `Id`
  CHANGELOG.md
  wgpu/src/lib.rs
Labels: PR: needs back-porting

#5199 Improve Instance::available_backend_features() on macOS.
  wgpu/src/lib.rs
Labels: PR: needs back-porting

#5222 [wgpu-core] Compute minimum binding size correctly for arrays.
  CHANGELOG.md
  tests/tests/buffer.rs
  wgpu-core/src/validation.rs
Labels: area: validation, area: correctness

#5218 Add max_color_attachments and max_color_attachment_bytes_per_sample
  wgpu-core/src/command/bundle.rs
  wgpu-core/src/command/render.rs
  wgpu-core/src/device/resource.rs
  wgpu-core/src/validation.rs
  wgpu-hal/src/dx12/adapter.rs
  wgpu-hal/src/gles/adapter.rs
  wgpu-hal/src/metal/adapter.rs
  wgpu-hal/src/metal/mod.rs
  wgpu-hal/src/vulkan/adapter.rs
  wgpu-info/src/human.rs
  wgpu-types/src/lib.rs
  wgpu/src/backend/webgpu.rs
Labels: area: validation

#5169 Revert "docs: inline `document-features` usage, remove dep."
  Cargo.lock
  Cargo.toml
  wgpu-core/Cargo.toml
  wgpu-core/src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/lib.rs
Labels: area: documentation

#5274 Validate that the view dimension of a multisampled texture binding is 2d
  wgpu-core/src/binding_model.rs
  wgpu-core/src/device/resource.rs
Labels: area: validation
