Repository gfx-rs/wgpu, pull requests merged in 2024-10, with the labels that each got.

#6346 [naga spv-out] Internal doc fixes for `back::spv::index`.
  naga/src/back/spv/index.rs
Labels: area: documentation, area: naga back-end, naga, lang: SPIR-V

#6336 [naga spv-out] Consolidate explanation of global wrapping.
  naga/src/back/spv/helpers.rs
  naga/src/back/spv/index.rs
  naga/src/back/spv/mod.rs
Labels: area: documentation, area: naga back-end, naga, lang: SPIR-V

#6387 [naga spv-out] Expand LocalType to permit pointers to matrices.
  naga/src/back/spv/block.rs
  naga/src/back/spv/image.rs
  naga/src/back/spv/mod.rs
  naga/src/back/spv/ray.rs
  naga/src/back/spv/subgroup.rs
  naga/src/back/spv/writer.rs
Labels: area: naga back-end, naga, kind: refactor, lang: SPIR-V

#6388 [naga spv-out] Simplify `Writer::get_pointer_id`.
  naga/src/back/spv/block.rs
  naga/src/back/spv/index.rs
  naga/src/back/spv/mod.rs
  naga/src/back/spv/writer.rs
Labels: area: naga back-end, naga, kind: refactor, lang: SPIR-V

#6389 [naga spv-out] Delete `BlockContext::is_intermediate`; use types.
  naga/src/back/spv/block.rs
Labels: area: naga back-end, naga, kind: refactor, lang: SPIR-V

#6398 chore: satisfy `unused_qualifications` (again)
  naga/src/back/spv/block.rs
Labels: kind: refactor

#6400 refactor: s/`once_cell::sync::OnceCell`/`std::sync::OnceLock` (as much as possible)
  wgpu-core/src/binding_model.rs
  wgpu-core/src/device/resource.rs
Labels: area: infrastructure, kind: refactor

#6401 refactor: fully qual. `size_of` usage
  examples/src/bunnymark/mod.rs
  examples/src/srgb_blend/mod.rs
Labels: kind: refactor

#6230 refactor(glsl-out): hoist new `if let TypeInner::Struct` out of `varying_required_features`
  naga/src/back/glsl/features.rs
Labels: api: gles, kind: refactor

#6352 Add a skeleton for directives that reports nice errors
  CHANGELOG.md
  Cargo.lock
  naga/Cargo.toml
  naga/src/front/wgsl/error.rs
  naga/src/front/wgsl/mod.rs
  naga/src/front/wgsl/parse/directive.rs
  naga/src/front/wgsl/parse/lexer.rs
  naga/src/front/wgsl/parse/mod.rs
Labels: kind: refactor

#6466 chore: mark `lock-analyzer` as `package.publish = false`
  lock-analyzer/Cargo.toml
Labels: area: ecosystem

#6465 v23.0.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  naga-cli/Cargo.toml
  naga/Cargo.toml
  naga/fuzz/Cargo.toml
  wgpu-core/Cargo.toml
  wgpu-hal/Cargo.toml
  wgpu-types/Cargo.toml
Labels: area: ecosystem, area: documentation

#6464 feat(naga-cli)!: init. logger to `INFO` by default
  Cargo.lock
  naga-cli/Cargo.toml
  naga-cli/src/bin/naga.rs
Labels: type: enhancement, naga

#6478 docs(RELEASE): remove refs. to `d3d12`
  RELEASE.md
Labels: area: infrastructure

#6480 fix(naga-cli): allow output files with `--stdin-file-path`
  CHANGELOG.md
  naga-cli/src/bin/naga.rs
Labels: type: bug, naga
