Repository gfx-rs/wgpu, pull requests merged in 2024-09, with the labels that each got.

#6209 [hal] Document some `CommandEncoder` trait methods.
  wgpu-hal/src/lib.rs
Labels: area: documentation

#6218 [naga] Update docs for private items.
  naga/src/front/wgsl/lower/mod.rs
  naga/src/front/wgsl/parse/ast.rs
  naga/src/front/wgsl/parse/mod.rs
Labels: area: documentation, naga, area: naga front-end, lang: WGSL

#6219 [core] Update docs for private items.
  wgpu-core/src/command/mod.rs
Labels: area: documentation

#6214 chore: satisfy `clippy::ref_as_ptr`
  wgpu-core/src/lock/observing.rs
Labels: area: infrastructure, kind: refactor

#6224 [ci] Re-enable `cargo doc --document-private-items` in CI
  .github/workflows/ci.yml
Labels: area: infrastructure, area: documentation

#6225 Resolve lints for Rust 1.78-1.81 that can be preempted before upgrade
  benches/benches/computepass.rs
  benches/benches/renderpass.rs
  benches/benches/resource_creation.rs
  wgpu-core/src/command/compute_command.rs
  wgpu-core/src/command/render_command.rs
  wgpu-core/src/track/texture.rs
  wgpu-hal/src/vulkan/instance.rs
  wgpu/src/api/queue.rs
  wgpu/src/backend/webgpu.rs
  wgpu/src/backend/wgpu_core.rs
  wgpu/src/context.rs
Labels: area: infrastructure

#6231 [naga] Document `snapshots::Targets::IR` and `ANALYSIS`.
  naga/tests/snapshots.rs
Labels: area: documentation, area: tests, naga

#6287 Update parking_lot dependency
  CHANGELOG.md
  Cargo.toml
Labels: area: infrastructure, area: ecosystem

#6294 docs(msl-out): note that Dawn also avoids loop UB like we do
  naga/src/back/msl/writer.rs
Labels: area: documentation, api: metal, lang: Metal

#6295 chore: suppress `unused_qualifications` for `wgpu_core::id` const. assertions
  wgpu-core/src/id.rs
Labels: area: infrastructure

#6297 chore: un-regress `unused_qualifications` lint in `naga::front::spv`
  naga/src/front/spv/error.rs
Labels: area: infrastructure

#6305 style: use `concat!(…)` in `DOWNLEVEL_*_MESSAGE`
  wgpu-core/src/lib.rs
Labels: kind: refactor

#6318 fix: handle `Queue::submit` non-fatally
  deno_webgpu/queue.rs
  tests/tests/regression/issue_6317.rs
  tests/tests/root.rs
  wgpu-core/src/device/queue.rs
  wgpu/src/backend/wgpu_core.rs
Labels: area: validation, area: correctness

#6328 [naga] Handle phony statements properly by treating them as named expressions
  naga/src/front/wgsl/lower/mod.rs
  naga/src/front/wgsl/parse/ast.rs
  naga/src/front/wgsl/parse/mod.rs
  naga/tests/in/phony_assignment.ron
  naga/tests/in/phony_assignment.wgsl
  naga/tests/out/glsl/phony_assignment.main.Compute.glsl
  naga/tests/out/hlsl/phony_assignment.hlsl
  naga/tests/out/hlsl/phony_assignment.ron
  naga/tests/out/msl/phony_assignment.msl
  naga/tests/out/spv/phony_assignment.spvasm
  naga/tests/out/wgsl/phony_assignment.wgsl
  naga/tests/snapshots.rs
Labels: area: naga back-end, naga, area: naga front-end, lang: WGSL

#6333 [naga] Permit only structs as binding array elements.
  naga/src/valid/type.rs
  naga/tests/validation.rs
Labels: type: bug, area: validation, naga
