Repository gfx-rs/wgpu, pull requests merged in 2024-11, with the labels that each got.

#6488 docs(CHANGELOG): ref. #4400 directly in v23 entry
  CHANGELOG.md
Labels: area: ecosystem, area: documentation

#6486 Fixes crash when there's a missing texture argument
  CHANGELOG.md
  naga/src/valid/analyzer.rs
  naga/tests/validation.rs
Labels: type: bug, naga, area: naga processing

#6505 fix(core): handle HAL errors from query set creation
  CHANGELOG.md
  wgpu-core/src/device/resource.rs
Labels: type: bug

#6508 fix(const_eval): don't panic when a `vecN` constructor's arg. count is less than N
  CHANGELOG.md
  naga/src/proc/constant_evaluator.rs
Labels: type: bug

#6450 Naga: add types to `InvalidBinaryOperandTypes` error msg
  CHANGELOG.md
  naga/src/valid/expression.rs
Labels: type: enhancement, area: validation, naga, kind: diagnostics

#6531 fix: allow non-filterable float on derived BGLs for texture binding usage w/ no sampler
  CHANGELOG.md
  wgpu-core/src/validation.rs
Labels: type: bug, area: correctness

#6535 don't set autoresizing mask on ios as that's not supported
  CHANGELOG.md
  wgpu-hal/src/metal/surface.rs
Labels: PR: needs back-porting

#6524 docs(diagnostic_filter): add more words to `DiagnosticFilterMap`
  naga/src/diagnostic_filter.rs
Labels: area: documentation, naga, area: naga front-end

#6545 [naga msl-out] Avoid UB by making all loops bounded.
  naga/src/back/msl/writer.rs
  naga/tests/out/msl/atomicCompareExchange.msl
  naga/tests/out/msl/boids.msl
  naga/tests/out/msl/break-if.msl
  naga/tests/out/msl/collatz.msl
  naga/tests/out/msl/control-flow.msl
  naga/tests/out/msl/do-while.msl
  naga/tests/out/msl/overrides-ray-query.msl
  naga/tests/out/msl/ray-query.msl
  naga/tests/out/msl/shadow.msl
Labels: type: bug, area: naga back-end, naga, lang: Metal

#6585 chore: preempt qualification lints again, Vulkan edition
  wgpu-hal/src/vulkan/device.rs
Labels: kind: refactor

#6588 Add `device_unregister_device_lost_closure`
  wgpu-core/src/device/global.rs
Labels: area: api, area: ecosystem

#6553 Improve binding error
  CHANGELOG.md
  wgpu-core/src/validation.rs
Labels: kind: diagnostics

#6607 chore(naga): suppress `irrefutable_let_patterns` for `EnableExtension` `match`ing in `Error::as_parse_error`
  naga/src/front/wgsl/error.rs
Labels: kind: refactor

#6626 [core] Simplify some buffer tracker utility methods
  wgpu-core/src/track/buffer.rs
Labels: kind: refactor
