Repository gfx-rs/wgpu, pull requests merged in 2024-07, with the labels that each got.

#5912 test: fix `wgpu-test` building by itself
  tests/Cargo.toml
Labels: area: infrastructure

#5909 refactor: use built-in `{integer}::power_of_two` methods
  wgpu-core/src/command/bundle.rs
  wgpu-core/src/conv.rs
  wgpu-core/src/device/resource.rs
  wgpu-core/src/track/mod.rs
Labels: kind: refactor

#5916 refactor: satisfy `missing_docs,clippy::empty_docs`
  wgpu-types/src/counters.rs
Labels: kind: refactor

#5914 chore: satisfy `clippy::manual_unwrap_or_default`
  naga/src/back/dot/mod.rs
Labels: kind: refactor

#5913 chore(clippy): satisfy `unused_qualifications`
  naga/src/front/spv/mod.rs
Labels: kind: refactor

#5931 [wgpu] Reorganize buffer mapping docs. Make example code work.
  wgpu/src/lib.rs
Labels: area: documentation

#5955 [core] Correct docs for `LifetimeTracker` and its `mapped` field.
  wgpu-core/src/device/life.rs
Labels: area: documentation

#5953 [core] Correctly check mipmap-filtering samplers against the layout.
  tests/tests/bind_groups.rs
  tests/tests/root.rs
  wgpu-core/src/device/resource.rs
Labels: area: validation

#5966 docs(CHANGELOG): backport 0.19.5 entries
  CHANGELOG.md
Labels: area: infrastructure, area: ecosystem

#6024 refactor: satisfy `clippy::missing_transmute_annotations`
  wgpu-core/src/instance.rs
  wgpu-hal/src/gles/device.rs
  wgpu-hal/src/metal/surface.rs
Labels: api: metal, api: gles, kind: refactor

#5148 feat: make `ProgrammableStage::entry_point` optional
  benches/benches/computepass.rs
  benches/benches/renderpass.rs
  examples/src/boids/mod.rs
  examples/src/bunnymark/mod.rs
  examples/src/conservative_raster/mod.rs
  examples/src/cube/mod.rs
  examples/src/hello_compute/mod.rs
  examples/src/hello_synchronization/mod.rs
  examples/src/hello_triangle/mod.rs
  examples/src/hello_workgroups/mod.rs
  examples/src/mipmap/mod.rs
  examples/src/msaa_line/mod.rs
  examples/src/render_to_texture/mod.rs
  examples/src/repeated_compute/mod.rs
  examples/src/shadow/mod.rs
  examples/src/skybox/mod.rs
  examples/src/srgb_blend/mod.rs
  examples/src/stencil_triangles/mod.rs
  examples/src/storage_texture/mod.rs
  examples/src/texture_arrays/mod.rs
  examples/src/timestamp_queries/mod.rs
  examples/src/uniform_values/mod.rs
  examples/src/water/mod.rs
  tests/src/image.rs
  tests/tests/bgra8unorm_storage.rs
  tests/tests/bind_group_layout_dedup.rs
  tests/tests/buffer.rs
  tests/tests/compute_pass_ownership.rs
  tests/tests/device.rs
  tests/tests/mem_leaks.rs
  tests/tests/nv12_texture/mod.rs
  tests/tests/occlusion_query/mod.rs
  tests/tests/partially_bounded_arrays/mod.rs
  tests/tests/pipeline.rs
  tests/tests/pipeline_cache.rs
  tests/tests/push_constants.rs
  tests/tests/regression/issue_3349.rs
  tests/tests/regression/issue_3457.rs
  tests/tests/regression/issue_5553.rs
  tests/tests/render_pass_ownership.rs
  tests/tests/scissor_tests/mod.rs
  tests/tests/shader/mod.rs
  tests/tests/shader/zero_init_workgroup_mem.rs
  tests/tests/shader_primitive_index/mod.rs
  tests/tests/shader_view_format/mod.rs
  tests/tests/subgroup_operations/mod.rs
  tests/tests/vertex_formats/mod.rs
  tests/tests/vertex_indices/mod.rs
  wgpu/src/api/compute_pipeline.rs
  wgpu/src/api/render_pipeline.rs
  wgpu/src/backend/webgpu.rs
  wgpu/src/backend/wgpu_core.rs
Labels: area: api, api: webgpu, area: cts

#6012 Error instead of panic in check bind
  CHANGELOG.md
  wgpu-core/src/command/bind.rs
  wgpu-core/src/lib.rs
  wgpu-core/src/utils.rs
Labels: PR: needs back-porting

#6052 Fix AnyDevice drop implementation dropping the wrong thing
  CHANGELOG.md
  wgpu-core/src/device/any_device.rs
Labels: PR: needs back-porting

#6020 Use workspace dependencies more.
  Cargo.toml
  naga-cli/Cargo.toml
  naga/Cargo.toml
  wgpu-core/Cargo.toml
  wgpu-hal/Cargo.toml
  wgpu-types/Cargo.toml
Labels: area: infrastructure

#6041 Fix error message in create_render_pass
  CHANGELOG.md
  wgpu/src/backend/wgpu_core.rs
Labels: PR: needs back-porting

#6064 [naga] Use cfg aliases to enable `naga::back::continue_forward`.
  naga/src/back/mod.rs
Labels: area: naga back-end, naga, lang: GLSL, lang: HLSL
