Repository gfx-rs/wgpu, pull requests merged in 2025-07, with the labels that each got.

#7909 fix(cts): use correct comparison direction for Git version check
  xtask/src/cts.rs
Labels: type: bug, area: infrastructure

#7939 Improve docs for `wgpu_types::InstanceFlags::VALIDATION`.
  wgpu-types/src/instance.rs
Labels: area: documentation

#7972 hal/vulkan: generate separate hash identity for Texture/TextureViews
  wgpu-hal/src/vulkan/adapter.rs
  wgpu-hal/src/vulkan/command.rs
  wgpu-hal/src/vulkan/device.rs
  wgpu-hal/src/vulkan/instance.rs
  wgpu-hal/src/vulkan/mod.rs
Labels: PR: needs back-porting

#7990 [naga, wgpu-core] Add some docs for Naga validator creation.
  naga/src/valid/mod.rs
  wgpu-core/src/device/mod.rs
Labels: area: documentation, naga

#7989 [naga] Make Naga tests build when no features are enabled.
  naga/tests/naga/validation.rs
Labels: area: tests, naga
