Repository gfx-rs/wgpu, pull requests merged in 2025-08, with the labels that each got.

#8053 test(deno_webgpu): add `--release` to `cargo xtask cts`
  xtask/src/cts.rs
Labels: type: enhancement, area: infrastructure, area: cts, area: deno

#8062 docs(release-checklist): sync backporting label name with current one
  docs/release-checklist.md
Labels: area: infrastructure

#8063 docs(release-checklist): include `This release includes `crate`, …` in the `CHANGELOG`, too
  docs/release-checklist.md
Labels: area: infrastructure

#8087 [hal] Minor doc clarification.
  wgpu-hal/src/lib.rs
Labels: area: documentation

#8075 docs: Add more overview documentation to `Buffer` and usages.
  wgpu-types/src/lib.rs
  wgpu/src/api/buffer.rs
Labels: type: enhancement, area: documentation

#8136 [naga] Introduce `KeywordSet` and `CaseInsensitiveKeywordSet`.
  CHANGELOG.md
  naga/src/back/glsl/keywords.rs
  naga/src/back/glsl/mod.rs
  naga/src/back/hlsl/keywords.rs
  naga/src/back/hlsl/writer.rs
  naga/src/back/msl/keywords.rs
  naga/src/back/msl/writer.rs
  naga/src/back/wgsl/writer.rs
  naga/src/keywords/wgsl.rs
  naga/src/proc/keyword_set.rs
  naga/src/proc/mod.rs
  naga/src/proc/namer.rs
  naga/src/racy_lock.rs
Labels: area: naga processing
