Repository gfx-rs/wgpu, pull requests merged in 2025-02, with the labels that each got.

#7039 [naga] Require hashbrown's serde feature as a dev-dependency.
  naga/Cargo.toml
Labels: area: tests, naga

#7070 [naga] Simplify iterator construction in `type_expression_tandem`.
  naga/src/arena/mod.rs
  naga/src/arena/unique_arena.rs
  naga/src/compact/mod.rs
Labels: naga, kind: refactor, area: naga middle-end

#6906 [naga] Add a review checklist.
  CONTRIBUTING.md
  REVIEW-CHECKLIST.md
Labels: naga

#7218 Update `REPO_MSRV` to 1.85
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/generate.yml
  Cargo.toml
  README.md
  examples/standalone/01_hello_compute/Cargo.toml
  examples/standalone/02_hello_window/Cargo.toml
  naga/src/back/spv/layout.rs
  naga/src/front/spv/mod.rs
  naga/xtask/Cargo.toml
  rust-toolchain.toml
  tests/src/expectations.rs
  wgpu-core/src/command/ray_tracing.rs
  wgpu-hal/Cargo.toml
  wgpu-hal/src/dx12/device.rs
  wgpu-hal/src/vulkan/device.rs
  wgpu/src/api/buffer.rs
  xtask/Cargo.toml
Labels: area: infrastructure

#7248 Refactor Wrapped
  naga/src/back/hlsl/help.rs
  naga/src/back/hlsl/mod.rs
Labels: kind: refactor
